notifications:
    email: false

language: python
python: 3.6
script:
        - num_errors=`flake8 - --max-line-length=120 \;| wc -l`
        - |
            if [ $num_errors -eq 0 ]; then
              true 
            else
              echo "$errors"
              false 
            fi
